name: Explicitly Reading and Using Exit Codes in Expressions

on: push

jobs:
  dump-context:
    runs-on: ubuntu-latest
    steps:
      #this isn't exit code, but it is exit message
      - name: Dump job context 
        run: echo '${{ toJSON(job) }}'
      - name: Run on Failure
        if: failure()
        run: echo "Failure"
      - name: Run on Success
        env: 
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"

    