name: Testing Katalon Run-Time
on:
  push:
    branches:
      - master
  schedule:
    #Cron expression for 5:00 PM MST
    - cron: '17 21 * * *'
  

jobs:
  build:
    runs-on: windows-latest
    steps:
    #Pull most recent repo to examine test suites
    - name: Pull from Repo
      uses: actions/checkout@v1
    #Begin Test Execution
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '7.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/Simple Test Suite Collection" -apiKey= ${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true'
    #Email on Success
    - name: Successful Test
      if: success()
      run : echo "This is where we will email success"
    #Email on Failure
    - name: Failed Test
      if: cancelled()
      run: echo "This is where we will email failure"