name: Testing Katalon Run-Time
on: push
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Pull from Repo
      uses: actions/checkout@v1
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '7.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/Simple Test Suite Collection" -apiKey= ${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true'
    - name: Successful Test
      if: success()
      run : echo "This is where we will email success"
    - name: Failed Test
      #will only run if the successful test step is skipped
      if: canceled()
      run: echo "This is where we will email failure"