name: Shell Commands Action

on: [pull_request]

jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
          - name: Echo a String
            run: echo "Hello, World!"
          - name: multi-line script
            run: |
              node -v
              npm -v
          - name: python command ro print processor being used
            run: |
              import platform
              print(platform.processor())
            shell: python
    
    run-windows-command:
      runs-on: windows-latest
      #make this job run after jobs listed in array finish successfully
      needs: ['run-shell-command']
      steps:
        - name: Directory Windows
          run: Get-Location
        - name: Directory Bash
          run: pwd
          shell: bash
    
    this-job-will-fail:
      runs-on: ubuntu-latest
      steps:
        - name: break the job
          run: echoo "Hello"
    
    and-this-job-will-not-run:
      runs-on: ubuntu-latest
      needs: [this-job-will-fail]
      steps: 
        - name: doesn't matter
          run: echo "this won't run"

    this-job-will-pass:
      runs-on: ubuntu-latest
      steps:
        - name: pass the job
          run: echo "Success!"
    
    and-this-job-will-run:
      runs-on: ubuntu-latest
      needs: [this-job-will-pass]
      steps: 
        - name: success
          run: echo "this runs!"


