name: Implicitly Reading Exit Codes Using Steps in Series

on: push

jobs:
  first-job-success:
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo "Success!"
  
  first-job-fail:
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: eco "Failure!"

  second-job-success:
    runs-on: ubuntu-latest
    needs: [first-job-success]
    steps:
      - name: second sucess
        run: echo "Success!"

  second-job-failure:
    runs-on: ubuntu-latest
    needs: [first-job-fail]
    steps:
      - name: second fail
        run: echo "Failure!"
