name: Team Swift Workflow

on: #dispatch event/pull request and scheduled time
  push

jobs: 
  pull-most-recent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 #checkout will checkout the most recent code
      - name: pull from repo
        run: |
          pwd
          ls

  email-results:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd/action-send-mail@v3.6.1
      with:
        server_address: smtp.gmail.com
        server_port: 465
        subject: Action Results
        to: Colton.Klable@travelport.com
        from: GitHub Actions
        body: ${{ toJSON(job) }}

