name: Team Swift Workflow

on: #dispatch event/pull request and scheduled time
  push


jobs: 
  pull-most-recent-and-email:
    runs-on: ubuntu-latest
    steps:
      - name: update repo
        uses: actions/checkout@v1 #checkout will checkout the most recent code
      - name: pull from repo
        run: |
          pwd
          ls
      - name: test job
        env: 
          JOB_CONTEXT: ${{ toJSON(job) }}
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$JOB_CONTEXT"
          echo "$GITHUB_CONTEXT"
      - name: send passing email
        id: email
        if: success()
        run: echo "Email sent"
        # uses: dawidd6/action-send-mail@v3.6.1
        # with:
        #   server_address: smtp.gmail.com
        #   server_port: 465
        #   subject: Action Results
        #   to: Colton.Klable@travelport.com
        #   from: GitHub Actions
        #   body: ${{ toJSON(job) }}
      - name: send failing email
        #only run is email step doesn't run
        if: cancelled() 
        run: echo "fail"

